# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ebb45e56aa8f68ccab5bb2f0ec0bde79"
name = "first-scaffold-remix-app"
application_url = "https://streams-breaks-technician-speeds.trycloudflare.com"
embedded = true
handle = "first-scaffold-remix-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

#PRODUCT CREATION
  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

#ORDER CREATION
  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_orders,read_orders,write_inventory,read_locations"

[auth]
redirect_urls = ["https://streams-breaks-technician-speeds.trycloudflare.com/auth/callback", "https://streams-breaks-technician-speeds.trycloudflare.com/auth/shopify/callback", "https://streams-breaks-technician-speeds.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
